config/routes.rb
Rails.application.routes.draw do
  root to: 'urls#index'

  get ':shortened_url', to: 'urls#show', param: :shortened_url, as: :show
  get ':shortened_url/info', to: 'urls#info', param: :shortened_url, as: :info

  resources :urls, only: [:index, :create], param: :shortened_url
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
    has_many :url_visits, dependent: :destroy

    before_validation :create_shortened_url


    # Format the original URL
    def original_url_formatted
        url = URI.parse(original_url)
        if url.scheme.present?
            original_url
        else
            'http://' + url.path
        end
    end


    private

        def create_shortened_url
            loop do
                self.shortened_url = SecureRandom.hex(2)
                break if Url.where(shortened_url: self.shortened_url).empty?
              end      
        end

end

app/models/url_visit.rb
class UrlVisit < ApplicationRecord
    belongs_to :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def index
    @urls = Url.all
  end

  def new
    @url = Url.new
  end

  def create
    # Get 
    original_url = url_params[:original_url]
    @url = Url.new(url_params)

    respond_to do |format|
      if @url.save
        format.html { redirect_to info_path(@url.shortened_url), notice: "Tiny, shortened, URL was successfully created." }
      else
        format.html { redirect_to root_path(original_url: original_url), status: :unprocessable_entity }
      end
    end
  end

  def show
    # Find url to show
    @url = Url.find_by(shortened_url: params[:shortened_url])
    # Create and find ip of the request 
    @url.url_visits.create(url: @url, ip_address: request.remote_ip)

    redirect_to @url.original_url_formatted
  end

  def info
    @url = Url.includes(:url_visits).find_by(shortened_url: params[:shortened_url])

    unless @url.present?
      redirect_to root_path, alert: 'Error, URL is not present.'
    end
  end

  private
    def url_params
      params.require(:url).permit(:original_url)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/_messages.html.erb
<% if flash[:notice] %>
    <div class="alert alert-primary"><%= notice %></div>
<% end %>
    <% if flash[:alert] %>
    <div class="alert alert-danger"><%= alert %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyUrlClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/messages' %>
    
    <%= yield %>
    
  </body>
</html>

app/views/urls/create.html.erb
<h1>Urls#create</h1>
<p>Find me in app/views/urls/create.html.erb</p>

app/views/urls/index.html.erb
<div class="row">

  <div class="col-2">
  </div>

  <div class="col-8">
    
    <div class="content">
      <h1>Enter a URL to be Shortened.</h1>

      <%= form_for Url.new, url: urls_path, method: :post do |f| %>
        <%= f.text_field :original_url, value: params[:original_url] %>
        <%= f.submit 'Submit' %>
      <% end %>

    </div>
    

  </div>

  <div class="col-2">
  </div>

</div>

app/views/urls/info.html.erb
<div class="row">

<div class="col-2"></div>

<div class="col-8 info-content">
  <h2>Shortened URL Information:</h2>

  Shortened url: <%= link_to show_url(@url.shortened_url), show_url(@url.shortened_url), target: :_blank %>
  <br>
  Original url: <%= link_to @url.original_url_formatted, @url.original_url_formatted %>

  <h2>URL Visits Information</h2>

  <% if @url.url_visits.present? %>
  <% @url.url_visits.each do |visitor| %>
    IP Address: <%= visitor.ip_address %> at <%= visitor.created_at.strftime('%d %b %Y, %H:%M %Z') %>
  <% end %>
  <% else %>
    No visitors yet!
  <% end %>

</div>

<div class="col-2"></div>

</div>

app/views/urls/new.html.erb
<h1>Urls#new</h1>
<p>Find me in app/views/urls/new.html.erb</p>

app/views/urls/show.html.erb
<h1>Urls#show</h1>
<p>Find me in app/views/urls/show.html.erb</p>